### ISSUE TITLE
jekyll-pagination does not work anymore with jekyll 1.1?

### ISSUE THREAD

**Issue by brtdv** [prometheus-ev/jekyll-pagination#3]
I updated my jekyll gem to version 1.1 but I'm currently having issues using jekyll-pagination?

When I execute the `jekyll` command, I get an ArgumentError

```
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-pagination-0.0.4/lib/jekyll/pagination.rb:65:in `pagination_enabled?': wrong number of arguments (1 for 2) (ArgumentError)
```

Full output: 

```
$ jekyll serve --watch --trace
Configuration file: /Users/bert/Projecten/personal/builtinbruges/web-blog/_config.yml
            Source: ./site
       Destination: ./web
      Generating... /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-pagination-0.0.4/lib/jekyll/pagination.rb:65:in `pagination_enabled?': wrong number of arguments (1 for 2) (ArgumentError)
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/generators/pagination.rb:13:in `generate'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/site.rb:203:in `block in generate'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/site.rb:202:in `each'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/site.rb:202:in `generate'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/site.rb:43:in `process'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/command.rb:18:in `process_site'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/commands/build.rb:23:in `build'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/commands/build.rb:7:in `process'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/bin/jekyll:96:in `block (2 levels) in <top (required)>'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.5/lib/commander/command.rb:180:in `call'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.5/lib/commander/command.rb:180:in `call'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.5/lib/commander/command.rb:155:in `run'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.5/lib/commander/runner.rb:402:in `run_active_command'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.5/lib/commander/runner.rb:78:in `run!'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.5/lib/commander/delegates.rb:7:in `run!'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.5/lib/commander/import.rb:10:in `block in <top (required)>'
```

I'm using this extension to be able to use pagination on another file instead of the default index.htm.

Also, according to [this pull request](https://github.com/mojombo/jekyll/pull/936), this should be possible in jekyll by default as of version 1.5, but I'm not really sure how long it will take for that version to be completed...

**Comment by blackwinter** [comment]
hi bert, i'm sorry but i don't see how we can make it work with Jekyll 1.1 -- at least we can try to make it compatible (9970cdf).

**Comment by brtdv** [comment]
Too bad. So basicly I'll have to wait until jekyll 1.5?

**Comment by blackwinter** [comment]
i'm afraid so. the other option would be to stay at 1.0.x. or try to find a way to make it work with 1.1 anyway (which probably involves fiddling with [generate](/mojombo/jekyll/blob/master/lib/jekyll/generators/pagination.rb#L12) and [template_page](/mojombo/jekyll/blob/master/lib/jekyll/generators/pagination.rb#L72)).

**Comment by zenorocha** [comment]
Same problem here, is there any fix?

**Comment by blackwinter** [comment]
no fix on our side and there's none to be expected, i'm afraid. Jekyll 1.1 just doesn't give us a suitable handle anymore.
